"""Scenario definitions for all tasks in the notification environment."""

TASK_SCENARIOS = {
    "signal_clarity": [
        {
            "app": "Slack",
            "category": "urgent",
            "sender_type": "boss",
            "urgency_hint": 0.95,
            "message_frequency": 1,
            "content_keywords": ["URGENT", "meeting", "now", "critical"],
            "user_state": "work",
            "active_tasks": ["sprint_review"],
            "sender_history": "reliable",
            "importance": "urgent",
            "expected_action": "escalate",
            "acceptable_action": "notify_now",
            "description": "Boss sends urgent Slack message during work hours",
            "feedback_correct": "Correct - boss + urgent keyword + reliable history = escalate immediately.",
            "feedback_wrong": "Missed it. Boss + urgent + reliable sender = always escalate.",
        },
        {
            "app": "Gmail",
            "category": "promotional",
            "sender_type": "marketing",
            "urgency_hint": 0.8,
            "message_frequency": 5,
            "content_keywords": ["50% OFF", "limited time", "sale", "offer"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Marketing email with fake urgency during relaxation",
            "feedback_correct": "Correct - promotional + spammy history + high frequency = silent.",
            "feedback_wrong": "Wrong. Promotional spam from known spammy sender = always silent.",
        },
        {
            "app": "HDFC Bank",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.9,
            "message_frequency": 1,
            "content_keywords": ["OTP", "transaction", "verify", "expires"],
            "user_state": "routine",
            "active_tasks": ["online_shopping"],
            "sender_history": "reliable",
            "importance": "high",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Bank OTP for an active online shopping transaction",
            "feedback_correct": "Correct - OTP expires fast; transactional + active shopping = notify_now.",
            "feedback_wrong": "Wrong. OTPs expire in 30s. Active shopping task = must notify_now immediately.",
        },
        {
            "app": "Netflix",
            "category": "promotional",
            "sender_type": "system",
            "urgency_hint": 0.3,
            "message_frequency": 2,
            "content_keywords": ["new series", "watch now", "trending"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Netflix recommendation notification while user is sleeping",
            "feedback_correct": "Correct - sleeping + promotional + no active task = silent always.",
            "feedback_wrong": "Wrong. Never interrupt sleep for promotional content.",
        },
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "friend",
            "urgency_hint": 0.4,
            "message_frequency": 2,
            "content_keywords": ["hey", "free tonight?", "plans"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "responsive",
            "importance": "medium",
            "expected_action": "notify_now",
            "acceptable_action": "delay",
            "description": "Friend asking about evening plans while user is relaxing",
            "feedback_correct": "Correct - social message + relax state + responsive history = notify_now.",
            "feedback_wrong": "Suboptimal. User is relaxing and this is a normal social message - notify_now or delay.",
        },
    ],
    "context_aware": [
        {
            "app": "Swiggy",
            "category": "contextual",
            "sender_type": "system",
            "urgency_hint": 0.85,
            "message_frequency": 3,
            "content_keywords": ["delivery", "2 minutes", "arriving", "order"],
            "user_state": "work",
            "active_tasks": ["ordered_food"],
            "sender_history": "reliable",
            "importance": "high",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Swiggy delivery arriving in 2 mins; user has active food order",
            "feedback_correct": "Correct - active food order makes delivery notification time-critical.",
            "feedback_wrong": "Wrong. User ordered food -> delivery arrival is time-critical -> notify_now.",
        },
        {
            "app": "Swiggy",
            "category": "promotional",
            "sender_type": "marketing",
            "urgency_hint": 0.7,
            "message_frequency": 4,
            "content_keywords": ["30% off", "order now", "lunch offer"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "spammy",
            "importance": "low",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Swiggy offer notification during deep focus with no active order",
            "feedback_correct": "Correct - no active order + deep_focus + promotional = silent.",
            "feedback_wrong": "Wrong. No active food order = this is just a promo. deep_focus = silent.",
        },
        {
            "app": "Cricbuzz",
            "category": "informative",
            "sender_type": "system",
            "urgency_hint": 0.5,
            "message_frequency": 6,
            "content_keywords": ["WICKET", "India", "over", "score"],
            "user_state": "relax",
            "active_tasks": ["watching_ipl"],
            "sender_history": "reliable",
            "importance": "high",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "IPL wicket alert while user is actively watching IPL",
            "feedback_correct": "Correct - user is actively watching IPL -> score updates are high value.",
            "feedback_wrong": "Wrong. active_tasks includes watching_ipl -> this is directly relevant.",
        },
        {
            "app": "Cricbuzz",
            "category": "informative",
            "sender_type": "system",
            "urgency_hint": 0.5,
            "message_frequency": 6,
            "content_keywords": ["WICKET", "India", "over", "score"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "reliable",
            "importance": "low",
            "expected_action": "silent",
            "acceptable_action": "delay",
            "description": "IPL score update during deep focus - user is NOT watching IPL",
            "feedback_correct": "Correct - no active IPL task + deep_focus = entertainment can wait.",
            "feedback_wrong": "Wrong. deep_focus + no active watching task = silent or delay.",
        },
        {
            "app": "Slack",
            "category": "informative",
            "sender_type": "colleague",
            "urgency_hint": 0.4,
            "message_frequency": 1,
            "content_keywords": ["can you", "review", "PR", "when free"],
            "user_state": "work",
            "active_tasks": ["in_meeting"],
            "sender_history": "responsive",
            "importance": "medium",
            "expected_action": "delay",
            "acceptable_action": "notify_now",
            "description": "Colleague asks for code review while user is in an active meeting",
            "feedback_correct": "Correct - in_meeting + non-urgent colleague message = delay until meeting ends.",
            "feedback_wrong": "Suboptimal. in_meeting makes this interruptive. Delay is the right call here.",
        },
    ],
    "adversarial_signals": [
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "colleague",
            "urgency_hint": 0.9,
            "message_frequency": 8,
            "content_keywords": ["urgent", "meme", "look at this", "dying"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "spammy",
            "importance": "low",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Colleague sends urgent meme during deep focus - fake urgency",
            "feedback_correct": "Correct - urgency is nullified by meme context + spammy history.",
            "feedback_wrong": "Wrong. meme + spammy + deep_focus = silent.",
        },
        {
            "app": "WhatsApp",
            "category": "urgent",
            "sender_type": "friend",
            "urgency_hint": 0.95,
            "message_frequency": 6,
            "content_keywords": ["call me", "NOW", "emergency", "hospital"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "urgent",
            "expected_action": "escalate",
            "acceptable_action": "notify_now",
            "description": "Spammy friend's 6th message is a genuine emergency",
            "feedback_correct": "Correct - hospital + emergency overrides spam history.",
            "feedback_wrong": "Wrong. Even spammy senders have real emergencies. hospital + emergency = escalate.",
        },
        {
            "app": "Slack",
            "category": "urgent",
            "sender_type": "boss",
            "urgency_hint": 0.95,
            "message_frequency": 2,
            "content_keywords": ["STILL WAITING", "where are you", "critical", "respond"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "reliable",
            "importance": "urgent",
            "expected_action": "escalate",
            "acceptable_action": None,
            "description": "Boss follows up on urgent message that was delayed",
            "feedback_correct": "Correct - repeated urgent message from boss = escalate regardless of focus.",
            "feedback_wrong": "Wrong. Follow-up urgent from boss must escalate.",
        },
        {
            "app": "Phone",
            "category": "urgent",
            "sender_type": "unknown",
            "urgency_hint": 0.85,
            "message_frequency": 1,
            "content_keywords": ["ASAP", "callback", "urgent", "important"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "unknown",
            "importance": "medium",
            "expected_action": "delay",
            "acceptable_action": None,
            "description": "Unknown sender requests urgent callback while user is sleeping",
            "feedback_correct": "Correct - unknown sender + sleeping = delay.",
            "feedback_wrong": "Wrong. Unknown + sleeping should be delayed, not escalated or ignored.",
        },
        {
            "app": "Swiggy",
            "category": "contextual",
            "sender_type": "system",
            "urgency_hint": 0.9,
            "message_frequency": 2,
            "content_keywords": ["delivery", "arrived", "at door", "collect now"],
            "user_state": "work",
            "active_tasks": ["ordered_food", "in_meeting"],
            "sender_history": "reliable",
            "importance": "high",
            "expected_action": "notify_now",
            "acceptable_action": "delay",
            "description": "Delivery arrived while user is in meeting and has active food order",
            "feedback_correct": "Correct - time-critical delivery wins; notify_now (not escalate).",
            "feedback_wrong": "Suboptimal. Active food order means notify_now or delay.",
        },
    ],
}

VALID_TASKS = list(TASK_SCENARIOS.keys())

TASK_WEIGHTS = {
    "signal_clarity": 1.0,
    "context_aware": 1.0,
    "adversarial_signals": 1.0,
}
