"""
Scenario definitions for all tasks in the notification environment.
25 scenarios per task — covering a wide range of real-world Indian apps,
user states, and adversarial patterns based on the PRD.
"""

TASK_SCENARIOS = {
    # ─────────────────────────────────────────────────────────────────────────
    # TASK 1: signal_clarity  (25 scenarios)
    # Purpose: Obvious, high-signal cases — the agent should get these right
    #          every time with minimal ambiguity.
    # ─────────────────────────────────────────────────────────────────────────
    "signal_clarity": [
        {
            "app": "Slack",
            "category": "urgent",
            "sender_type": "boss",
            "urgency_hint": 0.95,
            "message_frequency": 1,
            "content_keywords": ["URGENT", "meeting", "now", "critical"],
            "user_state": "work",
            "active_tasks": ["sprint_review"],
            "sender_history": "reliable",
            "importance": "urgent",
            "time_of_day": "morning",
            "expected_action": "escalate",
            "acceptable_action": "notify_now",
            "description": "Boss sends urgent Slack during work hours",
            "feedback_correct": "Correct — boss + urgent + reliable = escalate.",
            "feedback_wrong": "Missed it. Boss + urgent + reliable sender = always escalate.",
        },
        {
            "app": "Gmail",
            "category": "promotional",
            "sender_type": "marketing",
            "urgency_hint": 0.8,
            "message_frequency": 5,
            "content_keywords": ["50% OFF", "limited time", "sale", "offer"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Marketing email with fake urgency during relaxation",
            "feedback_correct": "Correct — promotional + spammy + high frequency = silent.",
            "feedback_wrong": "Wrong. Promotional spam from spammy sender = silent.",
        },
        {
            "app": "HDFC Bank",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.9,
            "message_frequency": 1,
            "content_keywords": ["OTP", "transaction", "verify", "expires"],
            "user_state": "routine",
            "active_tasks": ["online_shopping"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Bank OTP for active online shopping",
            "feedback_correct": "Correct — OTP expires in 30s; active shopping = notify_now.",
            "feedback_wrong": "Wrong. OTPs expire fast. Active shopping + transactional = notify_now.",
        },
        {
            "app": "Netflix",
            "category": "promotional",
            "sender_type": "system",
            "urgency_hint": 0.3,
            "message_frequency": 2,
            "content_keywords": ["new series", "watch now", "trending"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "night",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Netflix recommendation while user is sleeping",
            "feedback_correct": "Correct — sleeping + promotional = silent always.",
            "feedback_wrong": "Wrong. Never interrupt sleep for promotional content.",
        },
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "friend",
            "urgency_hint": 0.4,
            "message_frequency": 2,
            "content_keywords": ["hey", "free tonight?", "plans"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "responsive",
            "importance": "medium",
            "time_of_day": "evening",
            "expected_action": "notify_now",
            "acceptable_action": "delay",
            "description": "Friend asking about evening plans while user relaxes",
            "feedback_correct": "Correct — social message + relax + responsive = notify_now.",
            "feedback_wrong": "Suboptimal. Relaxing + normal social message = notify_now or delay.",
        },
        {
            "app": "PhonePe",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.95,
            "message_frequency": 1,
            "content_keywords": ["payment", "debited", "Rs.5000", "confirmed"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "morning",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Large UPI payment debit confirmation during work",
            "feedback_correct": "Correct — financial transaction alerts must always show immediately.",
            "feedback_wrong": "Wrong. Payment debited = transactional = notify_now.",
        },
        {
            "app": "Telegram",
            "category": "social",
            "sender_type": "marketing",
            "urgency_hint": 0.2,
            "message_frequency": 12,
            "content_keywords": ["join channel", "earn money", "crypto", "free"],
            "user_state": "deep_focus",
            "active_tasks": ["assignment"],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Crypto spam message during deep focus study",
            "feedback_correct": "Correct — spam + deep_focus + low urgency = silent.",
            "feedback_wrong": "Wrong. Obvious spam during deep focus = silent.",
        },
        {
            "app": "Google Pay",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.99,
            "message_frequency": 1,
            "content_keywords": ["fraud", "alert", "unusual activity", "block card"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "urgent",
            "time_of_day": "evening",
            "expected_action": "escalate",
            "acceptable_action": "notify_now",
            "description": "GPay fraud alert from bank system during relaxation",
            "feedback_correct": "Correct — fraud alert from reliable system = escalate immediately.",
            "feedback_wrong": "Wrong. Fraud alert = financial emergency = escalate.",
        },
        {
            "app": "Amazon",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.85,
            "message_frequency": 1,
            "content_keywords": ["OTP", "delivery", "confirm", "verify"],
            "user_state": "routine",
            "active_tasks": ["awaiting_delivery"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Amazon delivery OTP with active delivery task",
            "feedback_correct": "Correct — delivery OTP + active task = notify_now.",
            "feedback_wrong": "Wrong. Awaiting delivery + OTP = time-critical = notify_now.",
        },
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "family",
            "urgency_hint": 0.6,
            "message_frequency": 1,
            "content_keywords": ["how are you", "call tonight", "family dinner"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "afternoon",
            "expected_action": "delay",
            "acceptable_action": "notify_now",
            "description": "Family message during normal work hours",
            "feedback_correct": "Correct — non-urgent family message during work = delay is ideal.",
            "feedback_wrong": "Acceptable. Family + work = delay or notify_now.",
        },
        {
            "app": "LinkedIn",
            "category": "social",
            "sender_type": "system",
            "urgency_hint": 0.2,
            "message_frequency": 3,
            "content_keywords": ["new connection", "viewed profile", "job match"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "night",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "LinkedIn profile views while user is sleeping",
            "feedback_correct": "Correct — sleeping + non-urgent social = silent.",
            "feedback_wrong": "Wrong. Never interrupt sleep for LinkedIn activity.",
        },
        {
            "app": "YouTube",
            "category": "entertainment",
            "sender_type": "system",
            "urgency_hint": 0.1,
            "message_frequency": 4,
            "content_keywords": ["new video", "channel update", "watch now"],
            "user_state": "deep_focus",
            "active_tasks": ["exam_prep"],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "morning",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "YouTube recommendation during exam prep deep focus",
            "feedback_correct": "Correct — entertainment + deep_focus = silent.",
            "feedback_wrong": "Wrong. Entertainment during exam prep deep focus = always silent.",
        },
        {
            "app": "Phone",
            "category": "urgent",
            "sender_type": "boss",
            "urgency_hint": 0.98,
            "message_frequency": 3,
            "content_keywords": ["missed call", "call back", "ASAP", "critical"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "urgent",
            "time_of_day": "morning",
            "expected_action": "escalate",
            "acceptable_action": None,
            "description": "Boss repeatedly calling during work hours",
            "feedback_correct": "Correct — boss + repeated calls + reliable = escalate.",
            "feedback_wrong": "Wrong. Repeated missed calls from reliable boss = escalate.",
        },
        {
            "app": "Flipkart",
            "category": "promotional",
            "sender_type": "marketing",
            "urgency_hint": 0.5,
            "message_frequency": 6,
            "content_keywords": ["Big Billion Days", "70% off", "flash sale", "hurry"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Flipkart sale spam during relaxation",
            "feedback_correct": "Correct — promotional spam + spammy history = silent.",
            "feedback_wrong": "Wrong. Promotional sale spam = silent.",
        },
        {
            "app": "Spotify",
            "category": "entertainment",
            "sender_type": "system",
            "urgency_hint": 0.1,
            "message_frequency": 1,
            "content_keywords": ["new playlist", "daily mix", "recommended"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "night",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Spotify new playlist notification while sleeping",
            "feedback_correct": "Correct — sleeping + entertainment = silent.",
            "feedback_wrong": "Wrong. Entertainment notification during sleep = silent.",
        },
        {
            "app": "Reddit",
            "category": "social",
            "sender_type": "system",
            "urgency_hint": 0.1,
            "message_frequency": 8,
            "content_keywords": ["upvote", "comment", "trending post"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Reddit activity during deep focus coding",
            "feedback_correct": "Correct — social + deep_focus + low urgency = silent.",
            "feedback_wrong": "Wrong. Reddit during coding deep focus = silent.",
        },
        {
            "app": "SBI",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.95,
            "message_frequency": 1,
            "content_keywords": ["OTP", "net banking", "login", "verify"],
            "user_state": "routine",
            "active_tasks": ["bill_payment"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "morning",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Net banking OTP for active bill payment",
            "feedback_correct": "Correct — OTP + active task + transactional = notify_now.",
            "feedback_wrong": "Wrong. Active bill payment + OTP = must notify_now.",
        },
        {
            "app": "Gmail",
            "category": "informative",
            "sender_type": "system",
            "urgency_hint": 0.7,
            "message_frequency": 1,
            "content_keywords": ["salary", "credited", "payslip", "HR"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "morning",
            "expected_action": "notify_now",
            "acceptable_action": "delay",
            "description": "Salary credit notification from HR during work hours",
            "feedback_correct": "Correct — financial notification from reliable sender = notify_now.",
            "feedback_wrong": "Acceptable. Salary notification = notify_now or delay.",
        },
        {
            "app": "Paytm",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.8,
            "message_frequency": 1,
            "content_keywords": ["cashback", "Rs.50", "credited", "wallet"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "evening",
            "expected_action": "notify_now",
            "acceptable_action": "delay",
            "description": "Paytm cashback credited while relaxing",
            "feedback_correct": "Correct — financial + reliable + relax state = notify_now.",
            "feedback_wrong": "Acceptable. Cashback = notify_now or delay.",
        },
        {
            "app": "Snapchat",
            "category": "social",
            "sender_type": "system",
            "urgency_hint": 0.3,
            "message_frequency": 2,
            "content_keywords": ["streak", "ending soon", "reply", "snap"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "night",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Snapchat streak reminder while sleeping",
            "feedback_correct": "Correct — sleeping + trivial social = silent.",
            "feedback_wrong": "Wrong. A streak notification is not worth waking someone up.",
        },
        {
            "app": "Instagram",
            "category": "social",
            "sender_type": "system",
            "urgency_hint": 0.1,
            "message_frequency": 10,
            "content_keywords": ["liked your post", "new follower", "mention"],
            "user_state": "deep_focus",
            "active_tasks": ["work_report"],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "morning",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Instagram likes/follows during work report deep focus",
            "feedback_correct": "Correct — social engagement + deep_focus = silent.",
            "feedback_wrong": "Wrong. Instagram activity during deep focus work = silent.",
        },
        {
            "app": "Google Calendar",
            "category": "reminder",
            "sender_type": "system",
            "urgency_hint": 0.9,
            "message_frequency": 1,
            "content_keywords": ["doctor", "appointment", "30 minutes", "reminder"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": "escalate",
            "description": "Doctor appointment reminder 30 minutes away while relaxing",
            "feedback_correct": "Correct — time-bound appointment + reliable = notify_now.",
            "feedback_wrong": "Wrong. Missing a doctor appointment = worse than the interruption.",
        },
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "family",
            "urgency_hint": 0.3,
            "message_frequency": 15,
            "content_keywords": ["meme", "funny", "forward", "good morning"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "morning",
            "expected_action": "silent",
            "acceptable_action": "delay",
            "description": "Family group forwarded memes during deep focus coding",
            "feedback_correct": "Correct — family group meme + deep_focus = silent or delay.",
            "feedback_wrong": "Suboptimal. Meme forwards during deep focus = silent.",
        },
        {
            "app": "Blinkit",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.9,
            "message_frequency": 1,
            "content_keywords": ["order", "out for delivery", "10 minutes", "arriving"],
            "user_state": "routine",
            "active_tasks": ["ordered_groceries"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "morning",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Blinkit grocery delivery arriving in 10 mins with active order",
            "feedback_correct": "Correct — active grocery order + arriving = time-critical = notify_now.",
            "feedback_wrong": "Wrong. Active order + arriving in 10 mins = must notify_now.",
        },
        {
            "app": "X (Twitter)",
            "category": "social",
            "sender_type": "system",
            "urgency_hint": 0.1,
            "message_frequency": 20,
            "content_keywords": ["trending", "new follower", "liked tweet", "retweet"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "night",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Twitter engagement notifications while sleeping",
            "feedback_correct": "Correct — sleeping + trivial social engagement = silent.",
            "feedback_wrong": "Wrong. Twitter notifications do not justify waking someone up.",
        },
    ],

    # ─────────────────────────────────────────────────────────────────────────
    # TASK 2: context_aware  (25 scenarios)
    # ─────────────────────────────────────────────────────────────────────────
    "context_aware": [
        {
            "app": "Swiggy",
            "category": "contextual",
            "sender_type": "system",
            "urgency_hint": 0.85,
            "message_frequency": 3,
            "content_keywords": ["delivery", "2 minutes", "arriving", "order"],
            "user_state": "work",
            "active_tasks": ["ordered_food"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Swiggy delivery in 2 mins — user has active food order",
            "feedback_correct": "Correct — active food order = delivery is time-critical = notify_now.",
            "feedback_wrong": "Wrong. Active food order + delivery = time-critical = notify_now.",
        },
        {
            "app": "Swiggy",
            "category": "promotional",
            "sender_type": "marketing",
            "urgency_hint": 0.7,
            "message_frequency": 4,
            "content_keywords": ["30% off", "order now", "lunch offer"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Swiggy promo during deep focus — no active order",
            "feedback_correct": "Correct — no active order + deep_focus + promo = silent.",
            "feedback_wrong": "Wrong. No active food order + deep_focus = promo = silent.",
        },
        {
            "app": "Cricbuzz",
            "category": "informative",
            "sender_type": "system",
            "urgency_hint": 0.5,
            "message_frequency": 6,
            "content_keywords": ["WICKET", "India", "over", "score"],
            "user_state": "relax",
            "active_tasks": ["watching_ipl"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "evening",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "IPL wicket alert while actively watching IPL",
            "feedback_correct": "Correct — active watching task + score update = high value.",
            "feedback_wrong": "Wrong. active_tasks includes watching_ipl = directly relevant.",
        },
        {
            "app": "Cricbuzz",
            "category": "informative",
            "sender_type": "system",
            "urgency_hint": 0.5,
            "message_frequency": 6,
            "content_keywords": ["WICKET", "India", "over", "score"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "reliable",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": "delay",
            "description": "IPL score update during deep focus — NOT watching IPL",
            "feedback_correct": "Correct — no watching task + deep_focus = entertainment can wait.",
            "feedback_wrong": "Wrong. deep_focus + no active watching task = silent or delay.",
        },
        {
            "app": "Slack",
            "category": "informative",
            "sender_type": "colleague",
            "urgency_hint": 0.4,
            "message_frequency": 1,
            "content_keywords": ["can you", "review", "PR", "when free"],
            "user_state": "work",
            "active_tasks": ["in_meeting"],
            "sender_history": "responsive",
            "importance": "medium",
            "time_of_day": "morning",
            "expected_action": "delay",
            "acceptable_action": "notify_now",
            "description": "PR review request while in an active meeting",
            "feedback_correct": "Correct — in_meeting + non-urgent = delay.",
            "feedback_wrong": "Suboptimal. in_meeting + non-urgent colleague = delay.",
        },
        {
            "app": "Uber",
            "category": "contextual",
            "sender_type": "system",
            "urgency_hint": 0.9,
            "message_frequency": 2,
            "content_keywords": ["driver", "arriving", "2 min", "cab"],
            "user_state": "routine",
            "active_tasks": ["booked_cab"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "morning",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Uber driver arriving in 2 mins — active cab booking",
            "feedback_correct": "Correct — active cab booking + arriving = time-critical = notify_now.",
            "feedback_wrong": "Wrong. Booked cab + driver arriving = must notify_now.",
        },
        {
            "app": "Google Calendar",
            "category": "reminder",
            "sender_type": "system",
            "urgency_hint": 0.85,
            "message_frequency": 1,
            "content_keywords": ["meeting", "starts", "10 minutes", "Zoom"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "morning",
            "expected_action": "notify_now",
            "acceptable_action": "escalate",
            "description": "Zoom meeting in 10 minutes while deep-focusing",
            "feedback_correct": "Correct — time-bound reminder must break through deep focus.",
            "feedback_wrong": "Wrong. Missing a meeting because of deep focus is worse.",
        },
        {
            "app": "Zomato",
            "category": "promotional",
            "sender_type": "marketing",
            "urgency_hint": 0.6,
            "message_frequency": 3,
            "content_keywords": ["discount", "flat 40% off", "midnight hunger"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "night",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Zomato midnight promo while sleeping — no active order",
            "feedback_correct": "Correct — sleeping + promo + no order = silent.",
            "feedback_wrong": "Wrong. Never wake someone for food promotions.",
        },
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "girlfriend",
            "urgency_hint": 0.5,
            "message_frequency": 2,
            "content_keywords": ["hey", "miss you", "when coming", "call?"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "evening",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Girlfriend texts while user is relaxing",
            "feedback_correct": "Correct — trusted personal contact + relax state = notify_now.",
            "feedback_wrong": "Wrong. Trusted personal contact + relax = always notify_now.",
        },
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "girlfriend",
            "urgency_hint": 0.5,
            "message_frequency": 2,
            "content_keywords": ["hey", "miss you", "when coming", "call?"],
            "user_state": "deep_focus",
            "active_tasks": ["exam_prep"],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "afternoon",
            "expected_action": "delay",
            "acceptable_action": "notify_now",
            "description": "Same girlfriend text but user is deep-focusing for exam",
            "feedback_correct": "Correct — same contact but exam deep focus = delay is better.",
            "feedback_wrong": "Acceptable. Deep focus + exam = delay or notify_now.",
        },
        {
            "app": "Swiggy",
            "category": "contextual",
            "sender_type": "system",
            "urgency_hint": 0.85,
            "message_frequency": 2,
            "content_keywords": ["delivery", "arriving", "order", "2 minutes"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "delay",
            "acceptable_action": "silent",
            "description": "Swiggy delivery notification — user did NOT order food",
            "feedback_correct": "Correct — no active order = this is irrelevant = delay.",
            "feedback_wrong": "Wrong. No active food order = delivery notification is irrelevant.",
        },
        {
            "app": "Amazon",
            "category": "contextual",
            "sender_type": "system",
            "urgency_hint": 0.7,
            "message_frequency": 1,
            "content_keywords": ["out for delivery", "arriving today", "order", "package"],
            "user_state": "routine",
            "active_tasks": ["awaiting_delivery"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Amazon package out for delivery — user awaiting it",
            "feedback_correct": "Correct — active waiting task + package arriving = notify_now.",
            "feedback_wrong": "Wrong. User is awaiting the delivery — must notify_now.",
        },
        {
            "app": "Amazon",
            "category": "contextual",
            "sender_type": "system",
            "urgency_hint": 0.7,
            "message_frequency": 1,
            "content_keywords": ["out for delivery", "arriving today", "order", "package"],
            "user_state": "work",
            "active_tasks": ["in_meeting"],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "morning",
            "expected_action": "delay",
            "acceptable_action": "notify_now",
            "description": "Same Amazon delivery notification but user is in a meeting",
            "feedback_correct": "Correct — in_meeting + non-urgent package = delay.",
            "feedback_wrong": "Acceptable. In meeting + package = delay or notify_now.",
        },
        {
            "app": "Google Pay",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.9,
            "message_frequency": 1,
            "content_keywords": ["Rs.2000", "sent", "payment", "confirmed"],
            "user_state": "routine",
            "active_tasks": ["paying_bill"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "GPay payment confirmation during active bill payment",
            "feedback_correct": "Correct — active payment + financial = notify_now.",
            "feedback_wrong": "Wrong. Financial transaction during active payment task = notify_now.",
        },
        {
            "app": "Google Pay",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.9,
            "message_frequency": 1,
            "content_keywords": ["Rs.2000", "sent", "payment", "confirmed"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "night",
            "expected_action": "delay",
            "acceptable_action": None,
            "description": "GPay payment confirmation while sleeping (no active task)",
            "feedback_correct": "Correct — financial + no active task + sleeping = delay.",
            "feedback_wrong": "Wrong. Financial + no active task + sleeping = delay.",
        },
        {
            "app": "Slack",
            "category": "urgent",
            "sender_type": "boss",
            "urgency_hint": 0.95,
            "message_frequency": 1,
            "content_keywords": ["urgent", "need you", "right now", "critical"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "reliable",
            "importance": "urgent",
            "time_of_day": "afternoon",
            "expected_action": "escalate",
            "acceptable_action": None,
            "description": "Boss urgent Slack during deep focus coding",
            "feedback_correct": "Correct — boss + urgent + reliable overrides deep_focus = escalate.",
            "feedback_wrong": "Wrong. Boss urgent message always overrides deep focus.",
        },
        {
            "app": "Slack",
            "category": "urgent",
            "sender_type": "boss",
            "urgency_hint": 0.95,
            "message_frequency": 1,
            "content_keywords": ["urgent", "need you", "right now", "critical"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "urgent",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": "escalate",
            "description": "Same boss urgent Slack — user is relaxing",
            "feedback_correct": "Correct — relax + boss urgent = notify_now (no deep barrier).",
            "feedback_wrong": "Acceptable. Boss urgent + relax = notify_now or escalate.",
        },
        {
            "app": "Phone",
            "category": "social",
            "sender_type": "family",
            "urgency_hint": 0.6,
            "message_frequency": 1,
            "content_keywords": ["calling", "mom", "incoming call"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "evening",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Mom calling while user is relaxing in the evening",
            "feedback_correct": "Correct — trusted family + relax = notify_now.",
            "feedback_wrong": "Wrong. Family call + relaxing = notify_now.",
        },
        {
            "app": "Phone",
            "category": "social",
            "sender_type": "family",
            "urgency_hint": 0.6,
            "message_frequency": 1,
            "content_keywords": ["calling", "mom", "incoming call"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": "delay",
            "description": "Mom calling during deep focus — family breaks through",
            "feedback_correct": "Correct — family calls break through even deep focus = notify_now.",
            "feedback_wrong": "Acceptable. Family + deep focus = notify_now or delay.",
        },
        {
            "app": "Inshorts",
            "category": "informative",
            "sender_type": "system",
            "urgency_hint": 0.6,
            "message_frequency": 5,
            "content_keywords": ["breaking news", "earthquake", "alert", "India"],
            "user_state": "routine",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": None,
            "description": "Earthquake breaking news alert during routine activity",
            "feedback_correct": "Correct — safety-relevant news + routine = notify_now.",
            "feedback_wrong": "Wrong. Safety/disaster news = notify_now.",
        },
        {
            "app": "Inshorts",
            "category": "informative",
            "sender_type": "system",
            "urgency_hint": 0.6,
            "message_frequency": 5,
            "content_keywords": ["breaking news", "earthquake", "alert", "India"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "night",
            "expected_action": "delay",
            "acceptable_action": None,
            "description": "Same earthquake news while sleeping (no personal danger signal)",
            "feedback_correct": "Correct — news without personal danger signal + sleeping = delay.",
            "feedback_wrong": "Wrong. General news + sleeping = delay.",
        },
        {
            "app": "Flipkart",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.7,
            "message_frequency": 1,
            "content_keywords": ["order", "shipped", "out for delivery", "track"],
            "user_state": "routine",
            "active_tasks": ["ordered_product"],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "morning",
            "expected_action": "notify_now",
            "acceptable_action": "delay",
            "description": "Flipkart order shipped — user has active order task",
            "feedback_correct": "Correct — active order task + shipped update = notify_now.",
            "feedback_wrong": "Acceptable. Active ordered product + shipped = notify_now.",
        },
        {
            "app": "Flipkart",
            "category": "promotional",
            "sender_type": "marketing",
            "urgency_hint": 0.5,
            "message_frequency": 4,
            "content_keywords": ["sale", "discount", "buy now", "offer"],
            "user_state": "routine",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Flipkart promo push — no active order",
            "feedback_correct": "Correct — no active order + spammy + promotional = silent.",
            "feedback_wrong": "Wrong. Promo + no active task = silent.",
        },
        {
            "app": "Blinkit",
            "category": "contextual",
            "sender_type": "system",
            "urgency_hint": 0.9,
            "message_frequency": 2,
            "content_keywords": ["delivery", "partner", "at door", "collect"],
            "user_state": "work",
            "active_tasks": ["ordered_groceries", "in_meeting"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": "delay",
            "description": "Grocery delivery at door — in meeting but has active order",
            "feedback_correct": "Correct — active order wins over meeting = notify_now.",
            "feedback_wrong": "Acceptable. Active order + delivery = notify_now or delay.",
        },
        {
            "app": "YouTube",
            "category": "entertainment",
            "sender_type": "system",
            "urgency_hint": 0.4,
            "message_frequency": 1,
            "content_keywords": ["live stream", "India vs Pakistan", "starting now"],
            "user_state": "deep_focus",
            "active_tasks": ["study_session"],
            "sender_history": "reliable",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": "delay",
            "description": "Match live stream starting but user is studying",
            "feedback_correct": "Correct — no watching task + study deep focus = silent.",
            "feedback_wrong": "Suboptimal. No watching task + study deep focus = silent or delay.",
        },
    ],

    # ─────────────────────────────────────────────────────────────────────────
    # TASK 3: adversarial_signals  (25 scenarios)
    # ─────────────────────────────────────────────────────────────────────────
    "adversarial_signals": [
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "colleague",
            "urgency_hint": 0.9,
            "message_frequency": 8,
            "content_keywords": ["urgent", "meme", "look at this", "dying"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Colleague sends urgent meme — fake urgency",
            "feedback_correct": "Correct — urgency nullified by meme context + spammy history.",
            "feedback_wrong": "Wrong. meme + spammy + deep_focus = silent.",
        },
        {
            "app": "WhatsApp",
            "category": "urgent",
            "sender_type": "friend",
            "urgency_hint": 0.95,
            "message_frequency": 6,
            "content_keywords": ["call me", "NOW", "emergency", "hospital"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "urgent",
            "time_of_day": "afternoon",
            "expected_action": "escalate",
            "acceptable_action": "notify_now",
            "description": "Spammy friend's 6th message is a genuine emergency",
            "feedback_correct": "Correct — hospital + emergency overrides spam history.",
            "feedback_wrong": "Wrong. hospital + emergency = escalate regardless of spam history.",
        },
        {
            "app": "Slack",
            "category": "urgent",
            "sender_type": "boss",
            "urgency_hint": 0.95,
            "message_frequency": 2,
            "content_keywords": ["STILL WAITING", "where are you", "critical", "respond"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "reliable",
            "importance": "urgent",
            "time_of_day": "morning",
            "expected_action": "escalate",
            "acceptable_action": None,
            "description": "Boss follows up on urgent message that was delayed",
            "feedback_correct": "Correct — repeated urgent from boss = escalate regardless of focus.",
            "feedback_wrong": "Wrong. Follow-up urgent from boss must escalate.",
        },
        {
            "app": "Phone",
            "category": "urgent",
            "sender_type": "unknown",
            "urgency_hint": 0.85,
            "message_frequency": 1,
            "content_keywords": ["ASAP", "callback", "urgent", "important"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "unknown",
            "importance": "medium",
            "time_of_day": "night",
            "expected_action": "delay",
            "acceptable_action": None,
            "description": "Unknown sender requests urgent callback while sleeping",
            "feedback_correct": "Correct — unknown + sleeping = delay.",
            "feedback_wrong": "Wrong. Unknown + sleeping = delay, not escalate.",
        },
        {
            "app": "Swiggy",
            "category": "contextual",
            "sender_type": "system",
            "urgency_hint": 0.9,
            "message_frequency": 2,
            "content_keywords": ["delivery", "arrived", "at door", "collect now"],
            "user_state": "work",
            "active_tasks": ["ordered_food", "in_meeting"],
            "sender_history": "reliable",
            "importance": "high",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": "delay",
            "description": "Delivery arrived — in meeting but has active food order",
            "feedback_correct": "Correct — active order wins; notify_now.",
            "feedback_wrong": "Suboptimal. Active food order = notify_now or delay.",
        },
        {
            "app": "Instagram",
            "category": "social",
            "sender_type": "marketing",
            "urgency_hint": 0.75,
            "message_frequency": 10,
            "content_keywords": ["you won", "prize", "claim now", "congratulations"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "evening",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Fake prize/winner scam from spam sender",
            "feedback_correct": "Correct — prize scam + spammy = silent.",
            "feedback_wrong": "Wrong. 'You won' + spammy = scam = silent.",
        },
        {
            "app": "Phone",
            "category": "urgent",
            "sender_type": "family",
            "urgency_hint": 0.99,
            "message_frequency": 4,
            "content_keywords": ["fire", "accident", "call back", "injured"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "urgent",
            "time_of_day": "night",
            "expected_action": "escalate",
            "acceptable_action": None,
            "description": "Family calling about fire/accident at night",
            "feedback_correct": "Correct — fire + accident + family = escalate even during sleep.",
            "feedback_wrong": "Wrong. Emergency keywords from family override sleep = escalate.",
        },
        {
            "app": "Microsoft Teams",
            "category": "urgent",
            "sender_type": "boss",
            "urgency_hint": 0.88,
            "message_frequency": 1,
            "content_keywords": ["urgent", "client", "presentation", "now"],
            "user_state": "commuting",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "urgent",
            "time_of_day": "morning",
            "expected_action": "notify_now",
            "acceptable_action": "escalate",
            "description": "Boss urgent Teams message while commuting",
            "feedback_correct": "Correct — commuting + boss + urgent = notify_now.",
            "feedback_wrong": "Wrong. Boss + urgent during commute = notify_now at minimum.",
        },
        {
            "app": "WhatsApp",
            "category": "promotional",
            "sender_type": "marketing",
            "urgency_hint": 0.9,
            "message_frequency": 5,
            "content_keywords": ["WIN iPhone", "lottery", "click link", "selected"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Lottery/iPhone scam — fake urgency",
            "feedback_correct": "Correct — lottery scam + spammy = silent regardless of urgency hint.",
            "feedback_wrong": "Wrong. Lottery scam + spammy history = always silent.",
        },
        {
            "app": "SBI",
            "category": "transactional",
            "sender_type": "marketing",
            "urgency_hint": 0.9,
            "message_frequency": 3,
            "content_keywords": ["OTP", "account", "verify now", "click link"],
            "user_state": "routine",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Phishing OTP disguised as bank message — spammy sender",
            "feedback_correct": "Correct — bank OTP from spammy sender = phishing = silent.",
            "feedback_wrong": "Wrong. OTP from spammy sender = phishing attempt = silent.",
        },
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "colleague",
            "urgency_hint": 0.8,
            "message_frequency": 12,
            "content_keywords": ["important", "read this", "must see", "reel"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Colleague sending reels labelled 'important' — pattern spam",
            "feedback_correct": "Correct — spammy + reel content = silent despite 'important' label.",
            "feedback_wrong": "Wrong. Spammy colleague + reel content = silent.",
        },
        {
            "app": "Slack",
            "category": "social",
            "sender_type": "colleague",
            "urgency_hint": 0.85,
            "message_frequency": 1,
            "content_keywords": ["urgent", "quick question", "lunch?", "canteen"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": "delay",
            "description": "Colleague marks lunch invite as 'urgent' during deep focus",
            "feedback_correct": "Correct — 'urgent' label on lunch invite = fake urgency = silent.",
            "feedback_wrong": "Suboptimal. Lunch + deep focus = fake urgency = silent or delay.",
        },
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "family",
            "urgency_hint": 0.3,
            "message_frequency": 2,
            "content_keywords": ["good morning", "god bless", "forward", "share"],
            "user_state": "deep_focus",
            "active_tasks": ["work_deadline"],
            "sender_history": "reliable",
            "importance": "low",
            "time_of_day": "morning",
            "expected_action": "delay",
            "acceptable_action": "silent",
            "description": "Family good morning forward during work deadline deep focus",
            "feedback_correct": "Correct — trivial family forward + deep focus = delay.",
            "feedback_wrong": "Suboptimal. Trivial forward + deadline = delay or silent.",
        },
        {
            "app": "Slack",
            "category": "urgent",
            "sender_type": "boss",
            "urgency_hint": 0.7,
            "message_frequency": 1,
            "content_keywords": ["hey", "quick check", "status update", "when done"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "afternoon",
            "expected_action": "delay",
            "acceptable_action": "notify_now",
            "description": "Boss sends a non-critical status check during deep focus",
            "feedback_correct": "Correct — boss but medium urgency + deep focus = delay.",
            "feedback_wrong": "Acceptable. Medium urgency boss + deep focus = delay or notify_now.",
        },
        {
            "app": "Swiggy",
            "category": "contextual",
            "sender_type": "system",
            "urgency_hint": 0.8,
            "message_frequency": 1,
            "content_keywords": ["delivery", "nearby", "5 minutes", "order"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": "delay",
            "description": "Swiggy delivery notification — user never placed an order",
            "feedback_correct": "Correct — delivery + no active order = misdirected = silent.",
            "feedback_wrong": "Suboptimal. No active food order = delivery = irrelevant = silent.",
        },
        {
            "app": "HDFC Bank",
            "category": "transactional",
            "sender_type": "system",
            "urgency_hint": 0.99,
            "message_frequency": 1,
            "content_keywords": ["fraud", "blocked", "unauthorized", "Rs.15000"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "urgent",
            "time_of_day": "night",
            "expected_action": "escalate",
            "acceptable_action": None,
            "description": "Real bank fraud block alert at night — reliable bank sender",
            "feedback_correct": "Correct — real fraud from reliable bank = escalate even at night.",
            "feedback_wrong": "Wrong. Bank fraud = financial emergency = escalate always.",
        },
        {
            "app": "WhatsApp",
            "category": "promotional",
            "sender_type": "marketing",
            "urgency_hint": 0.95,
            "message_frequency": 1,
            "content_keywords": ["account hacked", "verify now", "click here", "security"],
            "user_state": "relax",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "evening",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Fake 'account hacked' scare from marketing/spam sender",
            "feedback_correct": "Correct — scare tactic from spammy sender = phishing = silent.",
            "feedback_wrong": "Wrong. 'Account hacked' from spammy marketing = phishing = silent.",
        },
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "colleague",
            "urgency_hint": 0.7,
            "message_frequency": 10,
            "content_keywords": ["call me", "right now", "need you", "please"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "responsive",
            "importance": "medium",
            "time_of_day": "afternoon",
            "expected_action": "notify_now",
            "acceptable_action": "escalate",
            "description": "10 rapid messages from responsive colleague — could be real issue",
            "feedback_correct": "Correct — 10 rapid messages + responsive history = treat as urgent.",
            "feedback_wrong": "Acceptable. High frequency + responsive = notify_now or escalate.",
        },
        {
            "app": "Phone",
            "category": "urgent",
            "sender_type": "unknown",
            "urgency_hint": 0.8,
            "message_frequency": 3,
            "content_keywords": ["missed call", "callback", "unknown number", "repeat"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "unknown",
            "importance": "medium",
            "time_of_day": "afternoon",
            "expected_action": "delay",
            "acceptable_action": "notify_now",
            "description": "Unknown number calling repeatedly during work (no emergency keywords)",
            "feedback_correct": "Correct — unknown + no emergency keywords + work = delay.",
            "feedback_wrong": "Acceptable. Unknown caller + work = delay or notify_now.",
        },
        {
            "app": "Discord",
            "category": "entertainment",
            "sender_type": "system",
            "urgency_hint": 0.2,
            "message_frequency": 15,
            "content_keywords": ["gaming", "join", "squad", "online now"],
            "user_state": "deep_focus",
            "active_tasks": ["exam_prep"],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "afternoon",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Discord gaming invite during exam prep deep focus",
            "feedback_correct": "Correct — gaming entertainment + exam deep focus = silent.",
            "feedback_wrong": "Wrong. Gaming invite during exam prep = always silent.",
        },
        {
            "app": "WhatsApp",
            "category": "social",
            "sender_type": "friend",
            "urgency_hint": 0.5,
            "message_frequency": 3,
            "content_keywords": ["important", "tell you something", "when free?", "need advice"],
            "user_state": "work",
            "active_tasks": ["in_meeting"],
            "sender_history": "reliable",
            "importance": "medium",
            "time_of_day": "morning",
            "expected_action": "delay",
            "acceptable_action": None,
            "description": "Friend wants to talk — in a meeting, non-emergency",
            "feedback_correct": "Correct — reliable friend but in_meeting + no emergency = delay.",
            "feedback_wrong": "Wrong. No emergency keywords + in_meeting = delay.",
        },
        {
            "app": "Slack",
            "category": "social",
            "sender_type": "colleague",
            "urgency_hint": 0.4,
            "message_frequency": 1,
            "content_keywords": ["happy birthday", "celebration", "team cake"],
            "user_state": "deep_focus",
            "active_tasks": ["work_deadline"],
            "sender_history": "responsive",
            "importance": "low",
            "time_of_day": "morning",
            "expected_action": "delay",
            "acceptable_action": "silent",
            "description": "Birthday message on Slack during deep focus deadline",
            "feedback_correct": "Correct — social celebration + deadline deep focus = delay.",
            "feedback_wrong": "Suboptimal. Birthday Slack + deep focus = delay or silent.",
        },
        {
            "app": "Google Calendar",
            "category": "reminder",
            "sender_type": "system",
            "urgency_hint": 0.5,
            "message_frequency": 1,
            "content_keywords": ["reminder", "gym", "workout", "6 AM"],
            "user_state": "sleeping",
            "active_tasks": [],
            "sender_history": "reliable",
            "importance": "low",
            "time_of_day": "night",
            "expected_action": "delay",
            "acceptable_action": None,
            "description": "Gym reminder calendar alert while sleeping",
            "feedback_correct": "Correct — non-emergency reminder + sleeping = delay.",
            "feedback_wrong": "Wrong. Non-emergency personal reminder + sleeping = delay.",
        },
        {
            "app": "WhatsApp",
            "category": "urgent",
            "sender_type": "family",
            "urgency_hint": 0.99,
            "message_frequency": 5,
            "content_keywords": ["dad", "collapsed", "hospital", "come now"],
            "user_state": "deep_focus",
            "active_tasks": ["coding_deadline"],
            "sender_history": "reliable",
            "importance": "urgent",
            "time_of_day": "afternoon",
            "expected_action": "escalate",
            "acceptable_action": None,
            "description": "Family says dad collapsed — genuine emergency during deep focus",
            "feedback_correct": "Correct — hospital + family emergency + reliable = escalate everything.",
            "feedback_wrong": "Wrong. Family emergency overrides every focus state = escalate.",
        },
        {
            "app": "Telegram",
            "category": "promotional",
            "sender_type": "marketing",
            "urgency_hint": 0.85,
            "message_frequency": 7,
            "content_keywords": ["BREAKING", "news alert", "share now", "viral"],
            "user_state": "work",
            "active_tasks": [],
            "sender_history": "spammy",
            "importance": "low",
            "time_of_day": "morning",
            "expected_action": "silent",
            "acceptable_action": None,
            "description": "Fake breaking news spam from spammy Telegram channel",
            "feedback_correct": "Correct — fake news spam + spammy channel = silent.",
            "feedback_wrong": "Wrong. Spammy sender + viral share content = always silent.",
        },
    ],
}

VALID_TASKS = list(TASK_SCENARIOS.keys())

TASK_WEIGHTS = {
    "signal_clarity": 1.0,
    "context_aware": 1.0,
    "adversarial_signals": 1.0,
}

# Set to 25 to run all scenarios per episode, or 5 for quick benchmark runs.
EPISODE_LENGTH = 25
